### ISSUE TITLE
3.1.12 - not starting correctly

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-zabbix#4]
This is the error message: 
`zabbix-server      | PHP Warning:  PHP Startup: Unable to load dynamic library 'event' (tried: /usr/lib/php8/modules/event (Error loading shared library /usr/lib/php8/modules/event: No such file or directory), /usr/lib/php8/modules/event.so (Error relocating /usr/lib/php8/modules/event.so: socket_import_file_descriptor: symbol not found)) in Unknown on line 0`

Version 3.1.11 works perfectly.

**Comment by tiredofit** [comment]
Darn it. We're seeing this happen internally on a few internal applications with no rhyme or reason. I'll check with the Ops team and find out more.
